name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Image Build and Tag
      - name: Build and Tag Docker Image
        run: |
          docker build -t flask-hola:${{ github.sha }} .
          docker tag actions-app:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker tag actions-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}:latest

      # Set up AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      # Push Docker Image to ECR
      - name: Push image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/actions-cicd:latest

      # Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push Docker Image to DockerHub
      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}:latest

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.${{ secrets.AWS_REGION }}.amazonaws.com/1.27.3/2023-09-11/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Update kubeconfig to access EKS
      - name: Update kubeconfig
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name actions-eks-cluster

      # Deploy to EKS
      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s-manifests/deployment.yaml
          kubectl apply -f k8s-manifests/service.yaml
